
@startuml
actor  "One Consumer" as OC
collections "Consumers" as C
participant "Consumer Server" as CSer
participant "Consumer Supervisor" as CS

participant "Publisher Supervisor" as PS



participant "Topic Supervisor" as TS
collections "Topics" as T
collections "Publishers" as P
participant "Exchanger" as E

collections "Publishers" as P
participant "Publisher Supervisor" as PS
participant "Publisher Server" as PSer
actor  "One Publisher" as OP

OC -> CSer: Start connection
CSer -> CS: New Consumer
CS -> C: Create Consumer

OC -> C: Subscribe
C -> E: Subscribe
E -> TS: Create topic if not present
TS -> T: Create Topic
E -> T: Add subscriber pointer


OP -> PSer: Start connection
PSer -> PS: New Publisher
PS -> P: Create Publisher
OP -> P: Send topic and message
P -> E:  Send topic and message


E -> T: Send Message
T -> E: Message : Subscribers[]
E -> C: Message to each Subscriber


OC -> C: Unsubscribe
C -> E: Unsubscribe temporarily or forever
E -> T: Delete subscriber pointer

@enduml
